export const SWAGGER_MESSAGES = {
  AUTH: {
    TAG: 'Authentication',
    REGISTER: 'Register a new guardian identity',
    LOGIN: 'Synchronize guardian access protocol',
    REGISTER_SUCCESS: 'Guardian identity successfully initialized',
    LOGIN_SUCCESS: 'Protocol synchronization successful',
  },
  PROJECTS: {
    TAG: 'Cultivation Layers (Projects)',
    CREATE: 'Initialize a new national cultivation layer',
    FIND_ALL: 'Aggregate all regional ecological projects',
    FIND_ONE: 'Retrieve specific cultivation layer specifications',
    UPDATE: 'Calibrate existing project parameters',
    DELETE: 'Safe-archive project from active oversight (Soft Delete)',
    STATS: 'Generate real-time ecological vitality metrics',
  },
  TASKS: {
    TAG: 'Ecosystem Pulses (Tasks)',
    CREATE: 'Dispatch a new ecological pulse',
    FIND_ALL: 'Monitor all pulses within a project node',
    FIND_ONE: 'Audit a specific task pulse',
    UPDATE: 'Adjust pulse parameters or status',
    DELETE: 'Safe-archive task from project cycle (Soft Delete)',
  },
  USERS: {
    TAG: 'Guardian Directory',
    FIND_ALL: 'Aggregate all registered guardian nodes',
    FIND_ONE: 'Query specific guardian identity data',
    PROFILE: 'Access authorized guardian profile',
  },
  ADMIN: {
    PROJECTS: {
      GET_ALL: 'Aggregate all projects across the continental grid',
      GET_STATS: 'Generate system-wide ecological vitality metrics',
      UPDATE: 'Architect override: Recalibrate any cultivation layer',
      DELETE: 'Architect override: Decommission any cultivation layer',
    },
    TASKS: {
      AUDIT: 'Architect audit: Deep-inspect any mission bud pulse',
      UPDATE: 'Architect override: Adjust any mission pulse parameters',
      DELETE: 'Architect override: Decommission any mission pulse',
    },
  },
  RESPONSES: {
    UNAUTHORIZED: 'Unauthorized. Bearer token required.',
    FORBIDDEN_ADMIN: 'Forbidden. Admin role required.',
    FORBIDDEN_PROJECT_OWNER: 'Forbidden. Only the project owner can perform this action.',
    FORBIDDEN_TASK_OWNER: 'Forbidden. Only creator, project owner, or assignee can perform this action.',
    PROJECT_NOT_FOUND: 'Project not found.',
    TASK_NOT_FOUND: 'Task not found.',
    PROJECT_CONFLICT: 'Project with this name already exists.',
    TASK_CONFLICT: 'Task with this title already exists in this project.',
    PAGINATED_PROJECTS: 'Paginated list of all projects.',
    PAGINATED_SYSTEM_PROJECTS: 'Paginated list of all projects across all users.',
    PAGINATED_TASKS: 'Paginated list of tasks for this project.',
    PROJECT_WITH_TASKS: 'The project with its tasks and owner.',
    TASK_WITH_ASSIGNEE: 'The task with assignee details.',
    PROJECT_UPDATED: 'Project updated successfully.',
    PROJECT_ADMIN_UPDATED: 'Project updated by admin override.',
    PROJECT_DELETED: 'Project soft-deleted successfully.',
    PROJECT_ADMIN_DELETED: 'Project soft-deleted by admin override.',
    TASK_CREATED: 'Task created and assigned.',
    TASK_UPDATED: 'Task updated successfully.',
    TASK_DELETED: 'Task soft-deleted successfully.',
    PROJECT_STATS: 'Real-time task breakdown by status and assignee.',
    SYSTEM_STATS: 'System-wide task counts grouped by status and assignee.',
  },
  PARAMS: {
    PAGE: 'Page number for pagination',
    LIMIT: 'Number of results per page',
    PROJECT_ID: 'Project UUID',
    TASK_ID: 'Task UUID',
    TASK_STATUS: 'Filter by task status',
    TASK_ASSIGNEE: 'Filter by assignee UUID',
  },
  FIELDS: {
    USER: {
      ID: 'The unique UUID of the guardian identity',
      NAME: 'The full name of the guardian ecologist',
      EMAIL: 'The unique email synchronized with the regional grid',
      PASSWORD: 'The authentication secret linked to the guardian node',
      ROLE: 'The role-based authorization sector assigned to this guardian',
      PROJECTS: 'The collection of projects overseen by this guardian',
      TASKS: 'The mission buds assigned to this guardian',
      CREATED_AT: 'Initial guardian synchronization timestamp',
      UPDATED_AT: 'Latest identity recalibration timestamp',
    },
    ROLE: {
      ID: 'The unique UUID of the authorization sector',
      NAME: 'The human-readable name of the role',
      SLUG: 'The unique slug identifier for the role',
      USERS: 'The collection of guardians assigned to this authorization sector',
    },
    PROJECTS: {
      ID: 'The unique UUID of the project node',
      NAME: 'The name of the national cultivation layer',
      DESCRIPTION: 'Detailed mission objectives for this project layer',
      OWNER: 'The guardian identity who oversees this project node',
      OWNER_ID: 'The UUID of the project overseer',
      TASKS: 'The collection of mission buds within this cultivation layer',
      CREATED_AT: 'Initial project activation timestamp',
      UPDATED_AT: 'Latest project parameter recalibration timestamp',
    },
    TASKS: {
      ID: 'The unique UUID of the mission bud',
      TITLE: 'The title of the ecological pulse',
      DESCRIPTION: 'Detailed mission parameters for this pulse',
      STATUS: 'The current growth state of the task',
      PRIORITY: 'The criticality level of this pulse',
      CREATOR: 'The guardian who initially dispatched this pulse',
      CREATOR_ID: 'The UUID of the pulse dispatcher',
      ASSIGNEE: 'The guardian currently overseeing this mission bud',
      ASSIGNEE_ID: 'The UUID of the guardian responsible for this pulse',
      PROJECT_ID: 'The UUID of the parent project layer',
      DUE_DATE: 'The deadline for mission completion',
      CREATED_AT: 'Initial pulse manifestation timestamp',
      UPDATED_AT: 'Latest pulse recalibration timestamp',
    },
  },
};

export const SWAGGER_EXAMPLES = {
  UUID: 'a1b2c3d4-e5f6-4a5b-b6c7-d8e9f0a1b2c3',
  AUTH: {
    NAME: 'Ecologist Jane',
    EMAIL: 'jane@taskflow.com',
    PASSWORD: 'password123',
    TOKEN: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...',
  },
  ROLE: {
    NAME: 'Field Coordinator',
    SLUG: 'user',
    ID: 'r1-uuid-protocol',
  },
  USER: {
    ID: 'u1-uuid-protocol',
    NAME: 'Ecologist Jane',
    EMAIL: 'jane@taskflow.com',
  },
  PROJECTS: {
    ID: 'p1-uuid-protocol',
    NAME: 'Reforestation Sector A',
    DESCRIPTION: 'Primary ecological restoration layer focusing on northern territories.',
  },
  TASKS: {
    ID: 't1-uuid-protocol',
    TITLE: 'Soil pH Analysis',
    DESCRIPTION: 'Analyze soil acidity levels for efficient sapling distribution.',
    ASSIGNEE_ID: 'user-uuid-123',
    PROJECT_ID: 'p1-uuid-protocol',
    DUE_DATE: '2026-04-30',
  },
  TIMESTAMPS: {
    INITIALIZATION: '2026-04-12T00:00:00Z',
    RECALIBRATION: '2026-04-12T12:00:00Z',
  },
};
