use anyhow::Result;
use sqlx::PgPool;
use uuid::Uuid;

use crate::domain::TelemetryEvent;

/// Persist a new telemetry event row and return the full inserted row
/// (including `created_at` generated by the database default).
pub async fn create_event(pool: &PgPool, event: &TelemetryEvent) -> Result<TelemetryEvent> {
    let row = sqlx::query_as::<_, TelemetryEvent>(
        "INSERT INTO telemetry_events \
             (id, tree_id, event_timestamp, height_cm, diameter_cm, health_status, idempotency_key) \
         VALUES ($1, $2, $3, $4, $5, $6, $7) \
         RETURNING id, tree_id, event_timestamp, height_cm, diameter_cm, \
                   health_status, idempotency_key, created_at",
    )
    .bind(event.id)
    .bind(event.tree_id)
    .bind(event.event_timestamp)
    .bind(event.height_cm)
    .bind(event.diameter_cm)
    .bind(&event.health_status)
    .bind(&event.idempotency_key)
    .fetch_one(pool)
    .await?;

    Ok(row)
}

/// Return all telemetry events for a given tree, newest first.
pub async fn list_by_tree(pool: &PgPool, tree_id: Uuid) -> Result<Vec<TelemetryEvent>> {
    let rows = sqlx::query_as::<_, TelemetryEvent>(
        "SELECT id, tree_id, event_timestamp, height_cm, diameter_cm, \
                health_status, idempotency_key, created_at \
         FROM telemetry_events \
         WHERE tree_id = $1 \
         ORDER BY event_timestamp DESC",
    )
    .bind(tree_id)
    .fetch_all(pool)
    .await?;

    Ok(rows)
}
